FROM python:3.9-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# Install any needed packages specified in requirements.txt
# Copy requirements.txt first to leverage Docker's layer caching
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt
  
RUN pip install --no-cache-dir -r Flask

# Copy the current directory contents into the container at /app
COPY . .

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run appy.py when the container launches
CMD ["python", "appy.py"]

# TO BUILD, go to cmd and "docker build -t hello-flask-app ."   
# TO RUN AFTER BUILD go to cmd and "docker run -p 8000:5000 hello-flask-app" 
# to test go to http://localhost:8000
